package com.github.tcking.giraffe.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.github.tcking.giraffe.model.KVTable;

import com.github.tcking.giraffe.model.KVTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig kVTableDaoConfig;

    private final KVTableDao kVTableDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        kVTableDaoConfig = daoConfigMap.get(KVTableDao.class).clone();
        kVTableDaoConfig.initIdentityScope(type);

        kVTableDao = new KVTableDao(kVTableDaoConfig, this);

        registerDao(KVTable.class, kVTableDao);
    }
    
    public void clear() {
        kVTableDaoConfig.getIdentityScope().clear();
    }

    public KVTableDao getKVTableDao() {
        return kVTableDao;
    }

}
